# Generated by Django 4.0 on 2022-01-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
